AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  shinagawa-shelter

  Sample SAM Template for shinagawa-shelter

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Environment:
      Variables:
        DB_HOST: !Ref DatabaseHost
        DB_NAME: !Ref DatabaseName
        DB_USER: !Ref DatabaseUser
        DB_PASSWORD: !Ref DatabasePassword

Parameters:
  DatabaseHost:
    Type: String
    Default: 127.0.0.1
  DatabaseName:
    Type: String
    Default: postgres
  DatabaseUser:
    Type: String
    Default: postgres
  DatabasePassword:
    Type: String
    Default: postgres
  DatasetUrls:
    Type: String
    Default: https://www.opendata.metro.tokyo.lg.jp/shinagawa/hinanjo.csv,http://www.city.shinagawa.tokyo.jp/ct/other000081500/ittokishugobasho.csv

Resources:
  ShelterSyncFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: resources/cmd/shelter-sync/
      Handler: shelter-sync
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        Schedule:
          Properties:
            Schedule: 'rate(5 minutes)'
            Name: ShelterSyncFunction
            Description: HelloWorldFunction
            Enabled: true
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DATASET_URLS: !Ref DatasetUrls
      Role: arn:aws:iam::880843126767:role/techboost-lambda
  ShelterApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: resources/cmd/shelter-api/
      Handler: shelter-api
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /search
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Role: arn:aws:iam::880843126767:role/techboost-lambda

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ShelterSyncFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt ShelterSyncFunction.Arn
  ShelterApiFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt ShelterApiFunction.Arn
