CREATE TABLE IF NOT EXISTS shelters (
  id SERIAL,
  facility_name TEXT UNIQUE,
  facility_name_en TEXT,
  category                    TEXT,
  prefecture                  TEXT,
  city                        TEXT,
  administrative_district     TEXT,
  address                     TEXT,
  address_kana                TEXT,
  telephone_number            TEXT,
  target_district             TEXT,
  target_district_description TEXT,
  latitude                    DECIMAL,
  longitude                   DECIMAL,
  above_sea_level             DECIMAL,
  facility_capacity           INTEGER,
  facility_height             DECIMAL,
  flood                       BOOLEAN,
  landslide                   BOOLEAN,
  storm_surge                 BOOLEAN,
  earthquake                  BOOLEAN,
  tsunami                     BOOLEAN,
  inundation                  BOOLEAN,
  fire                        BOOLEAN,
  eruption                    BOOLEAN,
  description                 TEXT,
  description_en              TEXT,
  standard_area_code          TEXT,
  created_at                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
